---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash /mnt/pve/NFS/apireq/addbalance/removebalapireq {{ email }} {{ amount }}
      register: result

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
