---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash /mnt/pve/NFS/vps/destroy/service_destroy {{ servicename }} {{ whosdeleting }} 
      register: result
      failed_when: result.rc != 1

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
