---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash "wakeonlan 00:80:64:e2:07:8a"
      register: result

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
