---
- name: Check disk space on all hosts and display it nicely
  hosts: nodes
  gather_facts: no
  tasks:
    - name: Get disk space for the main filesystem
      ansible.builtin.shell:
        cmd: df -h | grep '/dev/sda1' | awk '{print $2 " used, " $4 " available (" $5 " used) on the main filesystem"}'
      register: disk_space_main_fs

    - name: Show nicely formatted disk space results
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} - {{ disk_space_main_fs.stdout }}"
