---
- name: Run docker system prune on all servers
  hosts: your_host_group
  become: no 
  tasks:
    - name: Prune all unused Docker objects
      ansible.builtin.command:
        cmd: docker system prune --all --force --volumes
      register: prune_result

    - name: Show prune result
      ansible.builtin.debug:
        msg: "{{ prune_result.stdout }}"
