---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash /mnt/pve/NFS/vps/renew/auto_renew_add_days {{ servicename }} {{ howmanydays }}
      register: result
      failed_when: result.rc != 1

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
