---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: python3 /root/ilo/ilo_on.py
      register: result

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
