---
- hosts: proxmox
  tasks:
    - name: Execute command
      ansible.builtin.command:
        cmd: bash /mnt/pve/NFS/tt/tt_delete.sh {{ servicename }}
      register: result
      failed_when: result.rc != 1

    - name: Display output
      ansible.builtin.debug:
        var: result.stdout_lines
